// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace CheapestSkyscannerTicket.Services.DTO.Poll
{

    public class BookingDetailsLink
    {

        [JsonProperty("Uri")]
        public string Uri { get; set; }

        [JsonProperty("Body")]
        public string Body { get; set; }

        [JsonProperty("Method")]
        public string Method { get; set; }
    }

}
