// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace CheapestSkyscannerTicket.Services.DTO.Poll
{

    public class Currency
    {

        [JsonProperty("Code")]
        public string Code { get; set; }

        [JsonProperty("Symbol")]
        public string Symbol { get; set; }

        [JsonProperty("ThousandsSeparator")]
        public string ThousandsSeparator { get; set; }

        [JsonProperty("DecimalSeparator")]
        public string DecimalSeparator { get; set; }

        [JsonProperty("SymbolOnLeft")]
        public bool SymbolOnLeft { get; set; }

        [JsonProperty("SpaceBetweenAmountAndSymbol")]
        public bool SpaceBetweenAmountAndSymbol { get; set; }

        [JsonProperty("RoundingCoefficient")]
        public int RoundingCoefficient { get; set; }

        [JsonProperty("DecimalDigits")]
        public int DecimalDigits { get; set; }
    }

}
