// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace CheapestSkyscannerTicket.Services.DTO.Poll
{

    public class Itinerary
    {

        [JsonProperty("OutboundLegId")]
        public string OutboundLegId { get; set; }

        [JsonProperty("InboundLegId")]
        public string InboundLegId { get; set; }

        [JsonProperty("PricingOptions")]
        public PricingOption[] PricingOptions { get; set; }

        [JsonProperty("BookingDetailsLink")]
        public BookingDetailsLink BookingDetailsLink { get; set; }
    }

}
