// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace CheapestSkyscannerTicket.Services.DTO.Poll
{

    public class Leg
    {

        [JsonProperty("Id")]
        public string Id { get; set; }

        [JsonProperty("SegmentIds")]
        public int[] SegmentIds { get; set; }

        [JsonProperty("OriginStation")]
        public int OriginStation { get; set; }

        [JsonProperty("DestinationStation")]
        public int DestinationStation { get; set; }

        [JsonProperty("Departure")]
        public string Departure { get; set; }

        [JsonProperty("Arrival")]
        public string Arrival { get; set; }

        [JsonProperty("Duration")]
        public int Duration { get; set; }

        [JsonProperty("JourneyMode")]
        public string JourneyMode { get; set; }

        [JsonProperty("Stops")]
        public int[] Stops { get; set; }

        [JsonProperty("Carriers")]
        public int[] Carriers { get; set; }

        [JsonProperty("OperatingCarriers")]
        public int[] OperatingCarriers { get; set; }

        [JsonProperty("Directionality")]
        public string Directionality { get; set; }

        [JsonProperty("FlightNumbers")]
        public FlightNumber[] FlightNumbers { get; set; }
    }

}
