// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace CheapestSkyscannerTicket.Services.DTO.Poll
{

    public class PricingOption
    {

        [JsonProperty("Agents")]
        public int[] Agents { get; set; }

        [JsonProperty("QuoteAgeInMinutes")]
        public int QuoteAgeInMinutes { get; set; }

        [JsonProperty("Price")]
        public double Price { get; set; }

        [JsonProperty("DeeplinkUrl")]
        public string DeeplinkUrl { get; set; }
    }

}
