// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace CheapestSkyscannerTicket.Services.DTO.Poll
{

    public class Segment
    {

        [JsonProperty("Id")]
        public int Id { get; set; }

        [JsonProperty("OriginStation")]
        public int OriginStation { get; set; }

        [JsonProperty("DestinationStation")]
        public int DestinationStation { get; set; }

        [JsonProperty("DepartureDateTime")]
        public string DepartureDateTime { get; set; }

        [JsonProperty("ArrivalDateTime")]
        public string ArrivalDateTime { get; set; }

        [JsonProperty("Carrier")]
        public int Carrier { get; set; }

        [JsonProperty("OperatingCarrier")]
        public int OperatingCarrier { get; set; }

        [JsonProperty("Duration")]
        public int Duration { get; set; }

        [JsonProperty("FlightNumber")]
        public string FlightNumber { get; set; }

        [JsonProperty("JourneyMode")]
        public string JourneyMode { get; set; }

        [JsonProperty("Directionality")]
        public string Directionality { get; set; }
    }

}
